### ISSUE TITLE
ipv6 doesn't seem to work

### ISSUE THREAD

**Issue by zeratax** [lukebfox/nixops-hetznercloud#18]
I created a basic server based on the [trivial server example](https://github.com/lukebfox/nixops-hetznercloud/blob/master/examples/trivial-server.nix) as a ccx12 instance,

but trying to reach any ipv6 doesn't seem to work
```console
$ ping -6 google.com
ping: connect: Network is unreachable

$ curl -I -6 https://google.com
curl: (7) Couldn't connect to server
```

**Comment by lukebfox** [comment]
Thanks for the report!
